testing status check.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,12 +8,8 @@ jobs:
       - uses: actions/checkout@v2
       - name: Echo something
         run: echo "hi"
-      - name: Sleep
-        run: sleep 30
       - name: Curl localhost
-        run: curl http://localhost:9011
-      - name: Curl fusionauth
-        run: curl http://fusionauth:9011
+        run: curl --connect-timeout 2 -s -o /dev/null -w "%{http_code}" http://localhost:9011/api/status
     services:
       # Label used to access the service container
       postgres:
@@ -35,10 +31,10 @@ jobs:
         ports:
           - 9011:9011
         options: >-
-          --health-cmd bash -c '[[ $(curl --connect-timeout 2 -s -o /dev/null -w ''%{http_code}'' http://localhost:9011/api/status)" == 200 ]] || exit 1;' 
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 10
+          #--health-cmd 'curl --connect-timeout 2 -s -o /dev/null -w "%{http_code}" http://localhost:9011/api/status || exit 1;' 
+          #--health-interval 10s
+          #--health-timeout 5s
+          #--health-retries 10
         env:
           DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth
           DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
